USE DEVOPS;

CREATE TABLE IF NOT EXISTS `ENTIDADES` (
	ID_ENTIDADES INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(150),
	RAZAOSOCIAL VARCHAR(200),
	CNPJCPF VARCHAR(20),
	ENDERECO VARCHAR(150),
	BAIRRO VARCHAR(150),
	NUMERO INT,
	CEP VARCHAR(20),
	CIDADE VARCHAR(150),
	ESTADO VARCHAR(2)
	
);

CREATE TABLE IF NOT EXISTS `OPERADORES` (
	ID_OPERADORES INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100),
	SENHA VARCHAR(100),
	ATIVO TINYINT
);

SET character_set_client = utf8;
SET character_set_connection = utf8;
SET character_set_results = utf8;
SET collation_connection = utf8_general_ci;

INSERT INTO OPERADORES (NOME, SENHA, ATIVO) VALUES ('admin', 'admin', 1);